[package]
name = "oneocr-cli"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
image = "0.25.9"
libloading = "0.9.0"

[[bin]]
name = "oneocr"
path = "src/main.rs"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
